"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import importlib.util
import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]

DEBUG = os.environ.get("DEBUG", "false").lower() == "true"

ALLOWED_HOSTS = (
    os.environ.get("ALLOWED_HOSTS", "").split(",")
    if os.environ.get("ALLOWED_HOSTS")
    else []
)

CSRF_TRUSTED_ORIGINS = (
    os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if os.environ.get("CSRF_TRUSTED_ORIGINS")
    else []
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "posts",
    "pages",
]

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# debug_toolbar is a dev-only dependency; only enable it when it's installed
# so production images (built without dev deps) can still run with DEBUG=true.
if DEBUG and importlib.util.find_spec("debug_toolbar") is not None:
    INSTALLED_APPS += ["debug_toolbar"]
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
    INTERNAL_IPS = ["127.0.0.1"]

ROOT_URLCONF = "blog.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "blog.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "blog"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
#
# Static files (admin, DRF browsable API) are collected with `collectstatic`
# and served by WhiteNoise. User-uploaded media goes to object storage in
# production (see USE_S3 below) and is never served by Django.

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Switch media to S3-compatible object storage (AWS S3 / Cloudflare R2 /
# Backblaze B2) by setting USE_S3=true and the AWS_* vars. When off, media is
# stored on local disk (suitable for development only).
USE_S3 = os.environ.get("USE_S3", "false").lower() == "true"

STORAGES: dict[str, dict] = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

if USE_S3:
    # Private bucket by default: ImageField.url returns a presigned URL that
    # expires after AWS_QUERYSTRING_EXPIRE seconds. Set AWS_QUERYSTRING_AUTH=false
    # for a public bucket (then you can also serve via a CDN custom domain).
    AWS_QUERYSTRING_AUTH = (
        os.environ.get("AWS_QUERYSTRING_AUTH", "true").lower() == "true"
    )

    s3_options = {
        "bucket_name": os.environ["AWS_STORAGE_BUCKET_NAME"],
        "region_name": os.environ.get("AWS_S3_REGION_NAME") or None,
        "endpoint_url": os.environ.get("AWS_S3_ENDPOINT_URL") or None,
        "access_key": os.environ.get("AWS_ACCESS_KEY_ID") or None,
        "secret_key": os.environ.get("AWS_SECRET_ACCESS_KEY") or None,
        # SigV4 — required by newer AWS regions and S3-compatible providers
        # (R2/B2); the legacy SigV2 presign is rejected there.
        "signature_version": os.environ.get("AWS_S3_SIGNATURE_VERSION", "s3v4"),
        "querystring_auth": AWS_QUERYSTRING_AUTH,
        "querystring_expire": int(os.environ.get("AWS_QUERYSTRING_EXPIRE", "3600")),
        "location": os.environ.get("AWS_LOCATION", "media"),
        "file_overwrite": False,
    }

    # A CDN custom domain bypasses query-string signing, so it only applies to
    # public buckets. With signed URLs the link must hit the bucket/endpoint
    # host directly so the signature is honored.
    if not AWS_QUERYSTRING_AUTH:
        s3_options["custom_domain"] = os.environ.get("AWS_S3_CUSTOM_DOMAIN") or None

    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": s3_options,
    }


# Security
# https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# Production-only hardening (assumes HTTPS behind a TLS-terminating proxy).
if not DEBUG:
    # Trust the proxy's X-Forwarded-Proto so request.is_secure() works.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = (
        os.environ.get("SECURE_SSL_REDIRECT", "true").lower() == "true"
    )
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS — start small (e.g. 3600) when first enabling, then raise.
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
