# Generated by Django 6.0.6 on 2026-06-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_migrate_category_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
